<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Slim 3</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <form action="/tabela/" method="get">
        <div class="container">
            <div class="col-12">
                <div class="row">
                    <?php
                    foreach ($textos as $key => $texto) {
                        echo '<table class="table">';
                        echo '<thead>';
                        echo '<tr>';
                        echo '<th scope="col">#</th>';
                        echo '<th scope="col">Modelo</th>';
                        echo '<th scope="col">Marca</th>';
                        echo '<th scope="col">Ano</th>';
                        echo '</tr>';
                        echo '</thead>';
                        echo '<tbody>';
                        echo '<tr>';
                        echo '<th scope="row">' . $texto['id'] . '</th>';
                        echo '<td>' . $texto['modelo'] . '</td>';
                        echo '<td>' . $texto['marca'] . '</td>';
                        echo '<td>' . $texto['ano'] . '</td>';
                        echo '</tr>';
                        echo '</tbody>';
                        echo '</table>';
                    }
                    ?>
                </div>
            </div>
            <div class="text-center m-3">
                <a href="/atualizar/" class="btn btn-primary">Atualizar</a>
            </div>
            <div class="text-center m-3">
                <a href="/cadastro/" class="btn btn-primary">Cadastro</a>
            </div>
        </div>
    </form>
</body>

</html>